name: pust_printing_service

description: A new Flutter project for the PUST Printing Service app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  dio: ^5.1.0
  file_picker: ^4.7.0
  shared_preferences: ^2.0.11
  flutter_local_notifications: ^13.0.0
  # Add any other required packages here as needed.

flutter:
  uses-material-design: true
  assets:
    - assets/images/