// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHO5jf3SlKebgUIcMmxMEGjeRknZrLyYg',
    appId: '1:160543732289:web:6bfb84780933458a234cc0',
    messagingSenderId: '160543732289',
    projectId: 'pust-printing-service',
    authDomain: 'pust-printing-service.firebaseapp.com',
    storageBucket: 'pust-printing-service.firebasestorage.app',
    measurementId: 'G-01BTPE9F6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByauWQgHuUpefLSwQQmwgNIz_sZvaA6DI',
    appId: '1:160543732289:android:654760c62cb000d4234cc0',
    messagingSenderId: '160543732289',
    projectId: 'pust-printing-service',
    storageBucket: 'pust-printing-service.firebasestorage.app',
  );
}
